from utils.custom_exception import CustomException

class PipelineException(CustomException):
    pass
